#################
### AUTOSTART ###
#################

exec-once = hyprpaper
exec-once = hypridle
exec-once = waybar
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = wlsunset -l 19.43 -L -99.13 -t 4500
